#!/usr/bin/env python3

import os
import requests

url_base = "http://localhost:9797/"
requests.request( url=url_base+"push/"+os.environ["PAM_USER"], method="get" )
requests.request( url=url_base+"wait_for_queries", method="get" )
